version: '3.4'

services:
  project-dev:
    build:
      context: .
      target: dev
    ports:
      - '8000:8000'
    volumes:
      - './src:/srv/src'

  # Used by run-prod.sh & docker-build-prod.sh to locally test ENTRYPOINT ["/entrypoint.sh"], config.js etc
  project:
    build:
      context: .
      target: build

  project-prod:
    build:
      context: .
      target: prod
    ports:
      - '8000:80'
